# Generated by Django 2.1.7 on 2019-03-24 00:15

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='street')),
                ('number', models.CharField(max_length=10, verbose_name='number')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 0, 15, 37, 343004), verbose_name='Register date')),
            ],
            options={
                'verbose_name': 'address',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=5, verbose_name='Code')),
                ('phone_code', models.CharField(max_length=5, verbose_name='Phone code')),
            ],
            options={
                'verbose_name': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=4, verbose_name='Code')),
                ('phone_code', models.CharField(max_length=4, verbose_name='Phone code')),
            ],
            options={
                'verbose_name': 'country',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('shipment_price', models.FloatField(null=True, verbose_name='Price')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 0, 15, 37, 354953), verbose_name='Register date')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 0, 15, 37, 355143), verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('currency', models.CharField(blank=True, max_length=5, null=True, verbose_name='Currency')),
                ('quantity', models.FloatField(null=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit')),
                ('trip_date', models.DateField(null=True, verbose_name='Trip date')),
                ('cancel_date', models.DateField(null=True, verbose_name='Cancel date')),
                ('shipment_price', models.FloatField(verbose_name='Price')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 0, 15, 37, 352759), verbose_name='Register date')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 0, 15, 37, 352852), verbose_name='Update date')),
                ('from_city', models.ForeignKey(on_delete='From city', related_name='from_orders', to='beresoon.City')),
            ],
            options={
                'verbose_name': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('currency', models.CharField(blank=True, max_length=5, null=True, verbose_name='Currency')),
                ('quantity', models.FloatField(null=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 0, 15, 37, 344201), verbose_name='Register date')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 0, 15, 37, 344249), verbose_name='Update date')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_email', models.BooleanField(default=False, verbose_name='Notify email')),
                ('notify_app', models.BooleanField(default=True, verbose_name='Notify app')),
                ('notify_product_update', models.BooleanField(default=True, verbose_name='Notify product update')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 0, 15, 37, 348295), verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'setting',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('selfie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Selfie')),
                ('facebook', models.NullBooleanField(verbose_name='Facebook')),
                ('birth_date', models.DateField(null=True, verbose_name='Birth date')),
                ('passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport')),
                ('id_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID card')),
                ('id_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID number')),
                ('biography', models.TextField(blank=True, max_length=200, null=True, verbose_name='Biography')),
            ],
            options={
                'verbose_name': 'UsersBer',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='user',
            field=models.ForeignKey(on_delete='User Ber', related_name='user_setting', to='beresoon.Users'),
        ),
        migrations.AddField(
            model_name='photos',
            name='product',
            field=models.ForeignKey(on_delete='product', related_name='products_photos', to='beresoon.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete='product', related_name='products_orders', to='beresoon.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='to_city',
            field=models.ForeignKey(on_delete='To city', related_name='to_orders', to='beresoon.City'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete='Requester', related_name='user_orders', to='beresoon.Users'),
        ),
        migrations.AddField(
            model_name='offers',
            name='order',
            field=models.ForeignKey(on_delete='order', related_name='orders_offers', to='beresoon.Orders'),
        ),
        migrations.AddField(
            model_name='offers',
            name='traveler',
            field=models.ForeignKey(on_delete='traveler', related_name='traveler_offers', to='beresoon.Users'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete='country', related_name='city_country', to='beresoon.Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete='city', related_name='city_address', to='beresoon.City'),
        ),
    ]
